### ISSUE TITLE
download csv does not contain columns titles

### ISSUE THREAD

**Issue by hedb** [wix/quix#218] opened 2020-01-16 17:13 UTC

**Comment by frolovv** [comment] 2020-01-16 22:55
@hedb i couldn't reproduce on master branch. 

example of bigquery sql : 
```sql
WITH Timestamps AS (
  SELECT TIMESTAMP '2005-01-03 12:34:56' AS timestamp UNION ALL
  SELECT TIMESTAMP '2007-12-31' UNION ALL
  SELECT TIMESTAMP '2009-01-01' UNION ALL
  SELECT TIMESTAMP '2009-12-31' UNION ALL
  SELECT TIMESTAMP '2017-01-02' UNION ALL
  SELECT TIMESTAMP '2017-05-26'
)
SELECT
  timestamp,
  EXTRACT(ISOYEAR FROM timestamp) AS isoyear,
  EXTRACT(ISOWEEK FROM timestamp) AS isoweek,
  EXTRACT(YEAR FROM timestamp) AS year,
  EXTRACT(WEEK FROM timestamp) AS week
FROM Timestamps
ORDER BY timestamp;
```

csv result of both run & download and run-into-quix-and-then-download :
```csv
"timestamp","isoyear","isoweek","year","week"
"1104755696.0","2005","1","2005","1"
"1199059200.0","2008","1","2007","52"
"1230768000.0","2009","1","2009","0"
"1262217600.0","2009","53","2009","52"
"1483315200.0","2017","1","2017","1"
"1495756800.0","2017","21","2017","21"

```

same csv result when running query in playground

**Comment by antonpod** [comment] 2020-01-19 09:36
This one is also fixed in the master branch.

**Closed** 2020-02-05 13:21 UTC
